package com.lm.ldar.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.lm.ldar.entity.Enterprise;
import com.lm.ldar.entity.Factory;
import com.lm.ldar.entity.User;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig enterpriseDaoConfig;
    private final DaoConfig factoryDaoConfig;

    private final UserDao userDao;
    private final EnterpriseDao enterpriseDao;
    private final FactoryDao factoryDao;



    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);
        // 用户
        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);
        // 企业
        enterpriseDaoConfig = daoConfigMap.get(EnterpriseDao.class).clone();
        enterpriseDaoConfig.initIdentityScope(type);
        // 厂区
        factoryDaoConfig = daoConfigMap.get(FactoryDao.class).clone();
        factoryDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        enterpriseDao = new EnterpriseDao(enterpriseDaoConfig, this);
        factoryDao = new FactoryDao(factoryDaoConfig,this);

        registerDao(User.class, userDao);
        registerDao(Enterprise.class, enterpriseDao);
        registerDao(Factory.class,factoryDao);
    }
    
    public void clear() {
        userDaoConfig.clearIdentityScope();
        enterpriseDaoConfig.clearIdentityScope();
        factoryDaoConfig.clearIdentityScope();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public EnterpriseDao getEnterpriseDao() {
        return enterpriseDao;
    }

    public FactoryDao getFactoryDao() {
        return factoryDao;
    }

}
